services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: always

  back-end:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_USER=devflow
      - POSTGRES_PASSWORD=32gdF.2`HR'n
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=devflow_db
      - POSTGRES_PORT=5432
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: devflow
      POSTGRES_PASSWORD: 32gdF.2`HR'n
      POSTGRES_DB: devflow_db
    ports:
      - "5432:5432"
    volumes:
      - ./back/init-db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    restart: always

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=devflow_db
      - DB_POSTGRESDB_USER=devflow
      - DB_POSTGRESDB_PASSWORD=32gdF.2`HR'n
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=5&14^Ndgs1Gr
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_CORS_ENABLED=true
      - N8N_CORS_ORIGIN=http://localhost:8080
    volumes:
      - n8n_data:/home/node/.n8n
      - ./back/n8n-workflows:/workflows:ro
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data:
  n8n_data:
